app = "learning-accelerator-api"
primary_region = "iad"

[build]
  image = "registry.fly.io/learning-accelerator-api:latest"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/healthz"
    timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python manage.py migrate"
  strategy = "rolling"

[metrics]
  port = 9091
  path = "/metrics"